### ISSUE TITLE
error in spcabe returning solution with 0 components Error in value[[3L]](cond) : object 'outo' not found

### ISSUE THREAD

**Issue by hongwanzhang** [chrsigg/nsprcomp#1]
hi,
when I run:
bbe1 <- spcabe(data3,nd = 3)
data3 is matrix,col is sample,row is the gene,error is:
error in spcabe
returning solution with 0 components
Error in value[[3L]](cond) : object 'outo' not found

**Comment by chrsigg** [comment]
I don't understand your issue. `spcabe` is not part of the `nsprcomp` package (there is a function of that name in the `spca` package).

If you think that there is an issue in `nspcromp`, then please elaborate and provide a reproducible example.
