### ISSUE TITLE
nsprcomp gives different results when given the same equation

### ISSUE THREAD

**Issue by arthurgailes** [chrsigg/nsprcomp#2]
Hello,

As I've used this package, I've noticed that nsprcomp can give a different set of loadings the second time I run the function, even when using the same data. Is there a valid reason for this? 

I've used the provided example below, but in real-world data, the change can be significant enough to change the loadings quite dramatically. 

```
> set.seed(1)
> t <- nsprcomp(MASS::Boston, k = c(7, 5, 2, 2), nneg = TRUE, scale. = TRUE)
> t1 <- nsprcomp(MASS::Boston, k = c(7, 5, 2, 2), nneg = TRUE, scale. = TRUE)
> sum(t$rotation != t1$rotation)
[1] 20
```

**Comment by chrsigg** [comment]
PCA with sparsity and/or non-negativity constraints is a hard problem. `nsprcomp` performs local optimization of a random starting vector. You can use this to your advantage by increasing the number of random restarts (argument `nrestart`), and `nsprcomp` will return the best local optimum from all runs.

The Wikipedia [article on Sparse PCA ](https://en.wikipedia.org/wiki/Sparse_PCA) (and the papers it cites) provide the mathematical background.

If you need `t` and `t1` to be the same, you have to `set.seed` again before the second call to `nsprcomp`.

**Comment by arthurgailes** [comment]
Got it. Thanks for the quick response!
